  -- Table `cities`
DROP TABLE IF EXISTS `cities` ;
 
CREATE TABLE IF NOT EXISTS `cities` (
  `City` VARCHAR(50) NOT NULL,
  `Province` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`City`),
  `Is_main` TINYINT NOT NULL);
  

INSERT INTO `cities` (`City`, `Province`, `Is_main`) VALUES
('Colombo', 'Western', 1),
('Jaffna', 'Northern', 1),
('Kandy', 'Central', 1),
('Galle', 'Southern', 1),
('Anuradhapura', 'North Central', 1),
('Mannar', 'Northern', 0),
('Chavakachcheri', 'Northern', 0),
('Vavuniya', 'Northern', 0),
('Sri Jayewardenepura Kotte', 'Western', 1),
('Dehiwela-Mount Lavinia', 'Western', 1),
('Nuwara Eliya', 'Central', 0),
('Polonnaruwa', 'North Central', 0),
('Point Pedro', 'Northern', 0),
('Valvettithurai', 'Northern', 0),
('Kurunegala', 'North Western', 1),
('Ratnapura', 'Sabaragamuwa', 1),
('Badulla', 'Uva', 1),
('Bandarawela', 'Uva', 0),
('Happutalle', 'Uva', 0),
('Trincomalee', 'Eastern', 1),
('Kinniya', 'Eastern', 0),
('Batticaloa', 'Eastern', 1),
('Eravur', 'Eastern', 0),
('Kattankudy', 'Eastern', 0),
('Ampara', 'Eastern', 1),
('Kalmunai', 'Eastern', 0),
('Akkaraipattu', 'Eastern', 0),
('Embilipitiya', 'Sabaragamuwa', 0),
('Kegalle', 'Sabaragamuwa', 1),
('Balangoda', 'Sabaragamuwa', 0),
('Matale', 'Central', 1),
('Dambulla', 'Central', 0),
('Kalutata', 'Kalutara', 0),
('Matara', 'Southern', 1),
('Hambantota', 'Southern', 1),
('Chilaw', 'North Western', 1),
('Kuliyapitiya', 'North Western', 0),
('Gampaha', 'Western', 1),
('Negombo', 'Western', 0),
('Homagama', 'Western', 0);